on:
  push:
    branches:
    - main
  pull_request:
name: ci
jobs:
  checkout-env:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.8.1
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 8
    - run: java -version
    - run: |
        git submodule init
        git submodule update
    - name: Run tests in the repositories for the shared dependencies
      run: |
        mvn test --file google-auth-library-java
        mvn test --file java-core
  units:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        submodule:
          - java-accessapproval
          - java-iam-admin
          - java-iamcredentials
          - java-bigquery
    needs: checkout-env
    steps:
      - run: |
          mvn test --file ${{matrix.submodule}}

